// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFJntUQsVGOWK8G_ng3v3Y1UGMoE4Jwg',
    appId: '1:872146431594:web:ff69264727150564ac2413',
    messagingSenderId: '872146431594',
    projectId: 'first-project-40482',
    authDomain: 'first-project-40482.firebaseapp.com',
    storageBucket: 'first-project-40482.firebasestorage.app',
    measurementId: 'G-R0TJQL8255',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCM4oY88FQn9BoZT6urIbgXFc1Gk7AB0o',
    appId: '1:872146431594:android:945f9a122f6b932eac2413',
    messagingSenderId: '872146431594',
    projectId: 'first-project-40482',
    storageBucket: 'first-project-40482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOV5osqi9oJxFz0DAGqeaXclvAn8RFtU',
    appId: '1:872146431594:ios:d972bf9eb2961c00ac2413',
    messagingSenderId: '872146431594',
    projectId: 'first-project-40482',
    storageBucket: 'first-project-40482.firebasestorage.app',
    iosBundleId: 'com.example.cashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOV5osqi9oJxFz0DAGqeaXclvAn8RFtU',
    appId: '1:872146431594:ios:d972bf9eb2961c00ac2413',
    messagingSenderId: '872146431594',
    projectId: 'first-project-40482',
    storageBucket: 'first-project-40482.firebasestorage.app',
    iosBundleId: 'com.example.cashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAFJntUQsVGOWK8G_ng3v3Y1UGMoE4Jwg',
    appId: '1:872146431594:web:05ad1e4341ec4f59ac2413',
    messagingSenderId: '872146431594',
    projectId: 'first-project-40482',
    authDomain: 'first-project-40482.firebaseapp.com',
    storageBucket: 'first-project-40482.firebasestorage.app',
    measurementId: 'G-LZLZSQ0X8Z',
  );

}