// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgmWPG3ZH3O0kL6VAMSlQc8iUU98gyb4',
    appId: '1:740167142295:web:c92af104da7891ef00d2d2',
    messagingSenderId: '740167142295',
    projectId: 'pelaporkejadian-7a53d',
    authDomain: 'pelaporkejadian-7a53d.firebaseapp.com',
    databaseURL: 'https://pelaporkejadian-7a53d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pelaporkejadian-7a53d.firebasestorage.app',
    measurementId: 'G-LV7KJZK3YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxVUAcO1JDKo0SuQ8vd-isZdoB9XisgQ',
    appId: '1:740167142295:android:a25168b4579752a100d2d2',
    messagingSenderId: '740167142295',
    projectId: 'pelaporkejadian-7a53d',
    databaseURL: 'https://pelaporkejadian-7a53d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pelaporkejadian-7a53d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrmJ89V-5AEGe4QfQwvigXe92QV72_tQw',
    appId: '1:740167142295:ios:c2b3e1e838bf976000d2d2',
    messagingSenderId: '740167142295',
    projectId: 'pelaporkejadian-7a53d',
    databaseURL: 'https://pelaporkejadian-7a53d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pelaporkejadian-7a53d.firebasestorage.app',
    iosBundleId: 'com.example.pelaporankejadianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrmJ89V-5AEGe4QfQwvigXe92QV72_tQw',
    appId: '1:740167142295:ios:c2b3e1e838bf976000d2d2',
    messagingSenderId: '740167142295',
    projectId: 'pelaporkejadian-7a53d',
    databaseURL: 'https://pelaporkejadian-7a53d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pelaporkejadian-7a53d.firebasestorage.app',
    iosBundleId: 'com.example.pelaporankejadianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWgmWPG3ZH3O0kL6VAMSlQc8iUU98gyb4',
    appId: '1:740167142295:web:f5e9dcf081d8fb6200d2d2',
    messagingSenderId: '740167142295',
    projectId: 'pelaporkejadian-7a53d',
    authDomain: 'pelaporkejadian-7a53d.firebaseapp.com',
    databaseURL: 'https://pelaporkejadian-7a53d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pelaporkejadian-7a53d.firebasestorage.app',
    measurementId: 'G-NJGSNN9J0R',
  );

}