// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GQP6oHKAxoR0tywsWdQz0sYd00qAESs',
    appId: '1:625872643677:web:e3a5c399454a2507d58fb4',
    messagingSenderId: '625872643677',
    projectId: 'notes-a13db',
    authDomain: 'notes-a13db.firebaseapp.com',
    storageBucket: 'notes-a13db.firebasestorage.app',
    measurementId: 'G-5Y8EXMXQ14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpir9KMVpRrSqQdaB1bSksuSzjn4isOmo',
    appId: '1:625872643677:android:e5272872fc492e98d58fb4',
    messagingSenderId: '625872643677',
    projectId: 'notes-a13db',
    storageBucket: 'notes-a13db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8a6YXFOF9ibvkA-C2mpxojlUsL5-9Vo',
    appId: '1:625872643677:ios:0d8b33fe9b4646ebd58fb4',
    messagingSenderId: '625872643677',
    projectId: 'notes-a13db',
    storageBucket: 'notes-a13db.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu8a6YXFOF9ibvkA-C2mpxojlUsL5-9Vo',
    appId: '1:625872643677:ios:0d8b33fe9b4646ebd58fb4',
    messagingSenderId: '625872643677',
    projectId: 'notes-a13db',
    storageBucket: 'notes-a13db.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2GQP6oHKAxoR0tywsWdQz0sYd00qAESs',
    appId: '1:625872643677:web:7014e7ea76efc6b2d58fb4',
    messagingSenderId: '625872643677',
    projectId: 'notes-a13db',
    authDomain: 'notes-a13db.firebaseapp.com',
    storageBucket: 'notes-a13db.firebasestorage.app',
    measurementId: 'G-TC1R2VV2VQ',
  );

}